services:

  db:
    image: timescale/timescaledb-ha:pg16.3-ts2.16.0
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
