version: '3'

services:
  transmission:
    image: lscr.io/linuxserver/transmission
    environment:
      - USER=transmission
      - PASS=transmission
    ports:
      - 9091:9091
    restart: unless-stopped