name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    name: Setup the environment
    strategy:
      matrix:
        mix_env: ["prod", "dev"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1"
          elixir-version: "1.17"
      - run: MIX_ENV=${{matrix.mix_env}} mix deps.get --only ${{matrix.mix_env}}
      - run: MIX_ENV=${{matrix.mix_env}} mix compile --warnings-as-errors
      - name: cache build and deps
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ matrix.mix_env }}-${{ hashFiles('mix.lock') }}
          path: |
            ~/work/elixpeer/elixpeer/deps 
            ~/work/elixpeer/elixpeer/_build

  lint:
    name: Check formatting and style
    needs: [compile]
    strategy:
      matrix:
        mix_env: ["prod"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1"
          elixir-version: "1.17"
      - name: use cache from build
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-${{ matrix.mix_env }}-${{ hashFiles('mix.lock') }}
          path: |
            ~/work/elixpeer/elixpeer/deps 
            ~/work/elixpeer/elixpeer/_build
      - run: ls -la deps/
      - run: ls -la _build/
      - run: MIX_ENV=${{matrix.mix_env}} mix credo --strict
      - run: MIX_ENV=${{matrix.mix_env}} mix format --check-formatted
