name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    runs-on: elixir:1.17-otp-26
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." 
